server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: true
      uri: http://user:s3cret@localhost:8888

zuul:
  prefix: /api
  routes:
    users:
      path: /users/**
      serviceId: ms-users
  strip-prefix: false